'use client';

import Link from 'next/link';
import { Leaf } from 'lucide-react';
import { useState, useEffect } from 'react';

export default function TraceLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [year, setYear] = useState(new Date().getFullYear());

  useEffect(() => {
    setYear(new Date().getFullYear());
  }, []);
  return (
    <div className="flex flex-col min-h-screen bg-card">
      <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-4 md:px-6">
        <nav className="hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link
            href="/"
            className="flex items-center gap-2 text-lg font-semibold md:text-base"
          >
            <Leaf className="h-6 w-6 text-primary" />
            <span className="font-headline">AgriVision</span>
          </Link>
        </nav>
      </header>
      <main className="flex-1">{children}</main>
       <footer className="bg-background border-t">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-6 text-center text-muted-foreground text-sm">
          <p>This traceability report was generated by AgriVision and secured by blockchain technology.</p>
          <p>&copy; {year} AgriVision. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
