// ... existing code ...
<p className="text-sm text-muted-foreground">
  Scan results include &quot;as-is&quot; data from suppliers and &quot;verified&quot; checkpoints.
</p>
// ... existing code ...
